version: "3.8"
services:
    nodeserver:
        build:
            context: ./server/app
        ports:
            - "5000:5000"
    nginx:
        restart: always
        build:
            context: ./server/nginx
        ports:
            - "80:80"
    mongodb:
        restart: always
        build:
            context: ./server/mongodb
        ports:
            - "27017:27017"