version: "3.8"
services:
    # Backend
    nodeserver:
        restart: always
        depends_on:
            - mongodb
        build:
            context: ./server/app
        ports:
            - "5000:5000"
        env_file:
            - .env

    # Nginx
    nginx:
        restart: always
        build:
            context: ./server/nginx
        ports:
            - "80:80"

    # MongoDB
    mongodb:
        image: mongo:latest
        environment:
            - MONGODB_INITDB_ROOT_USERNAME=${MONGODB_INITDB_ROOT_USERNAME}
            - MONGODB_INITDB_ROOT_PASSWORD=${MONGODB_INITDB_ROOT_PASSWORD}
        ports:
            - "27017:27017"
        volumes:
            - mongodb_data:/data/db

    # minio
    minio:
        image: minio/minio:latest
        environment:
            - MINIO_ROOT_USER=${MINIO_ROOT_USER}
            - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
        ports:
            - "9000:9000"
        command: server --address 0.0.0.0:9000 /data
        volumes:
            - ./Minio/start:/data

volumes:
    mongodb_data:




