version: "3.8"
services:
    # User Service
    user-service:
        restart: always
        build:
            context: ./server/user
        ports:
            - "5000:5000"
        depends_on:
            - mongodb
        environment:
            - MONGO_URL=mongodb://${MONGODB_INITDB_ROOT_USERNAME}:${MONGODB_INITDB_ROOT_PASSWORD}@mongodb:27017
            - JWT_SECRET=${JWT_SECRET}
            - NODE_ENV=${NODE_ENV}
        env_file:
            - .env

    # Post Service
    post-service:
        restart: always
        build:
            context: ./server/post
        ports:
            - "5001:5001"
        depends_on:
            - mongodb
            - minio
        environment:
            - MONGO_URL=mongodb://${MONGODB_INITDB_ROOT_USERNAME}:${MONGODB_INITDB_ROOT_PASSWORD}@mongodb:27017
            - JWT_SECRET=${JWT_SECRET}
            - NODE_ENV=${NODE_ENV}
            - MINIO_ROOT_USER=${MINIO_ROOT_USER}
            - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
            - MINIO_ENDPOINT=minio
            - MINIO_PORT=9000
            - MINIO_BUCKET=${MINIO_BUCKET}
        env_file:
            - .env

    # Notification Service
    notification-service:
        restart: always
        build:
            context: ./server/notification
        ports:
            - "5002:5002"
        depends_on:
            - mongodb
        environment:
            - MONGO_URL=mongodb://${MONGODB_INITDB_ROOT_USERNAME}:${MONGODB_INITDB_ROOT_PASSWORD}@mongodb:27017
            - JWT_SECRET=${JWT_SECRET}
            - NODE_ENV=${NODE_ENV}
        env_file:
            - .env

    # Nginx Reverse Proxy
    nginx:
        restart: always
        build:
            context: ./server/nginx
        ports:
            - "80:80"
        depends_on:
            - user-service
            - post-service
            - notification-service

    # MongoDB
    mongodb:
        image: mongo:latest
        restart: always
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${MONGODB_INITDB_ROOT_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_INITDB_ROOT_PASSWORD}
        ports:
            - "27017:27017"
        volumes:
            - mongodb_data:/data/db

    # MinIO
    minio:
        image: minio/minio:latest
        container_name: minio
        command: server /data --console-address ":9001"
        ports:
        - "9000:9000"
        - "9001:9001"
        environment:
        - MINIO_ROOT_USER=minioadmin
        - MINIO_ROOT_PASSWORD=minioadmin
        volumes:
        - minio-data:/data
